### ISSUE TITLE
[ML] Slow runtime on Windows 2016

### ISSUE THREAD

**Issue by sophiec20** [elastic/ml-cpp#147] opened 2018-07-05 14:05 UTC
Whilst digging through the qa results, I noticed that runtime for the analytics appears significantly longer on Win 2016. This chart snippet is similar across smoke and buildly datasets and across all stack versions 6.3, 6.x, master. This is the median run time for last 30 days. 

![image](https://user-images.githubusercontent.com/4185750/42327230-28e66dba-8063-11e8-869e-7dbdd5af2389.png)

![image](https://user-images.githubusercontent.com/4185750/42327759-736be1d4-8064-11e8-9fa4-0b55532cc3f8.png)

@dolaru ran a benchmark on the qa host, so this does not appear to host related - although this is still a plausible reason.
> ran the `Cinebench` CPU benchmark on the windows nodes:
> - `windows_2012_r2` got  192
> - `windows_2016` got 183
> the difference is not significant enough to justify the massive difference in job runtimes.

For further investigation and is not necessarily yet classified as purely an ML issue.

**Comment by tveasey** [comment] 2018-07-05 14:11
Would be very helpful to get profiles for Windows and one other platform so we can see if there is any smoking gun.

**Comment by droberts195** [comment] 2018-07-11 11:57
A good next step for narrowing down what to investigate next would be this:

1. Hire two identically specced VMs, one with Windows 2012r2 and the other with Windows 2016
2. Create the same job on each and open them
3. Instead of creating a datafeed, post data to the job
4. When all data is posted, flush the jobs but do _not_ close them
5. Check the CPU time used in task manager for
  a. The Elasticsearch JVM
  b. The `autodetect` process for the job

The reason for posting data rather than using a datafeed is that the datafeed will automatically close the job and this will mean the task manager process stats disappear.  We want the `autodetect` process to hang around so we can inspect its CPU time used and possibly other task manager stats.

Different observations will imply different ways forward:

* If the `autodetect` process CPU time used is higher on Windows 2016 than on Windows 2012r2 but the JVM CPU time used is similar then that implies we need to profile the C++ code on Windows 2016 as per https://github.com/elastic/ml-cpp/issues/147#issuecomment-402735314
* If the JVM process CPU time used is higher on Windows 2016 than on Windows 2012r2 but the `autodetect` CPU time used is similar then that implies we need to profile the Java code on Windows 2016
* If the CPU time of both processes is higher on Windows 2016 than on Windows 2012r2 then that implies some systemic slowdown on the newer version of Windows, for example due to more security checks in some of Microsoft's code (I think this is unlikely because then surely we would find blogs on the subject)
* If the CPU time of neither process is higher on Windows 2016 than on Windows 2012r2 then this implies an I/O slowdown - this would tally with Cinebench not showing significant differences

**Comment by sophiec20** [comment] 2018-07-11 15:16
> The reason for posting data rather than using a datafeed is that the datafeed will automatically close the job 

If we set the datafeed to run in real-time (without an end date), then the job will stay open.

**Comment by hendrikmuhs** [comment] 2018-07-12 06:06
A difference of 2012 and 2016 is the ootb defender. It would be good and quite easy to turn it off for testing purposes. @dolaru how easy can [this](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016) be done on the qa host?

**Comment by sophiec20** [comment] 2018-07-12 17:02
2x instances were set up on GCP, same zone, same spec for win2012r2 datacenter and win2016 datacenter.

Job `mean(response) partition host @1m`, created using multi metric, where `runtime = finished_time - create_time` 
 
For the same job, the CPU time for autodetect was measured and this was virtually the same on both OS's.

However overall job runtimes were different .

On average, win2012r2 jobs ran 20s faster than win2016.

By adding win2016 Defender exceptions for the elasticsearch folders and processes java.exe, autodetect.exe and controller.exe, run times were improved by approx 10s.

The tests were naive - but they initially indicate that C++ code has not significantly slowed down on win2016. 

Other factors contributing to slow downs would be the effect of noisy neighbours on GCP and performance was also seen to degrade immediately after a reboot.

Next steps - add Defender exceptions to the win2016 QA nodes and check for differences to job runtimes over a wider variety of QA datasets.

**Comment by droberts195** [comment] 2024-01-11 10:31
The vast majority of the difference was shown to be caused by a virus checker.

We are more focused on Linux performance now as that's what our Cloud platform runs on, so it's unlikely we'll ever put more resource into Windows performance - as long as it runs moderately quickly on Windows and doesn't crash that's good enough. Therefore I'll close this issue.

**Closed by droberts195** 2024-01-11 10:31 UTC
Labels: >bug
