### ISSUE TITLE
[ML] Use rapidjson's key function where possible

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/ml-cpp#383] opened 2019-02-11 12:02 UTC
Rapidjson introduced in a later version a `Key(string)` function. It is no different that then `String(string)` function. However, it does communicate better the intention of writing a field name instead of a string value. It would make our JSON writing code more readable if we replaced all calls to `String` with `Key` where field names are written.

**Comment by GuptaTanisha** [comment] 2021-03-16 10:57
Please assign this to me.

**Comment by droberts195** [comment] 2021-03-16 11:42
@GuptaTanisha if you could make these changes that would be great!

**Comment by droberts195** [comment] 2021-06-10 17:58
@GuptaTanisha since we haven't heard from you for 3 months I've unassigned you so as not to discourage others from taking this on.  If you'd still like to contribute a PR for this then that would be fine even if the issue is not explicitly assigned to you.

**Comment by anishagg17** [comment] 2021-09-09 15:24
Seems like this issue is resolved, https://github.com/elastic/ml-cpp/blob/982df3e9bc813ef8b625adcbc03d1a00922d0397/lib/api/CJsonOutputWriter.cc#L880


Is there any file/code reference that anyone can share, I couldn't find use of `String(string)` function

**Comment by droberts195** [comment] 2021-09-20 11:42
@anishagg17 even though `Key` is used in some places now, there are still many places where the `Key` method could be used instead of `String`.  These are likely candidates:

```
bash-3.2$ grep '\.String([A-Z][A-Z][A-Z]' lib/*/*.cc
lib/api/CInferenceModelDefinition.cc:            writer.String(JSON_LT);
lib/api/CInferenceModelDefinition.cc:        writer.String(JSON_TARGET_TYPE_CLASSIFICATION);
lib/api/CInferenceModelDefinition.cc:        writer.String(JSON_TARGET_TYPE_REGRESSION);
lib/api/CJsonOutputWriter.cc:        m_Writer.String(RECORDS);
lib/api/CJsonOutputWriter.cc:        m_Writer.String(INFLUENCERS);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(BUCKET);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(JOB_ID);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(TIMESTAMP);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(ANOMALY_SCORE);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(INITIAL_SCORE);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(EVENT_COUNT);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(BUCKET_SPAN);
lib/api/CJsonOutputWriter.cc:        m_Writer.String(BUCKET_INFLUENCERS);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(PROCESSING_TIME);
lib/api/CJsonOutputWriter.cc:        m_Writer.String(SCHEDULED_EVENTS);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(QUANTILES);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(FLUSH);
lib/api/CJsonOutputWriter.cc:    m_Writer.String(LAST_FINALIZED_BUCKET_END);
lib/api/CModelSnapshotJsonWriter.cc:    m_Writer.String(MODEL_SNAPSHOT);
lib/api/CModelSnapshotJsonWriter.cc:    m_Writer.String(JOB_ID);
lib/api/CModelSnapshotJsonWriter.cc:    m_Writer.String(MIN_VERSION);
lib/api/CModelSnapshotJsonWriter.cc:    m_Writer.String(SNAPSHOT_ID);
lib/api/CModelSnapshotJsonWriter.cc:    m_Writer.String(SNAPSHOT_DOC_COUNT);
lib/api/CModelSnapshotJsonWriter.cc:    m_Writer.String(TIMESTAMP);
lib/api/CModelSnapshotJsonWriter.cc:    m_Writer.String(DESCRIPTION);
lib/api/CModelSnapshotJsonWriter.cc:        m_Writer.String(LATEST_RECORD_TIME);
lib/api/CModelSnapshotJsonWriter.cc:        m_Writer.String(LATEST_RESULT_TIME);
lib/api/CModelSnapshotJsonWriter.cc:    m_Writer.String(QUANTILES);
lib/api/CModelSnapshotJsonWriter.cc:    writer.String(JOB_ID);
lib/api/CModelSnapshotJsonWriter.cc:    writer.String(QUANTILE_STATE);
lib/api/CModelSnapshotJsonWriter.cc:    writer.String(TIMESTAMP);
lib/core/CJsonLogLayout.cc:    writer.String(LOGGER_NAME);
lib/core/CJsonLogLayout.cc:    writer.String(LOGGER);
lib/core/CJsonLogLayout.cc:    writer.String(TIMESTAMP_NAME);
lib/core/CJsonLogLayout.cc:    writer.String(LEVEL_NAME);
lib/core/CJsonLogLayout.cc:    writer.String(PID_NAME);
lib/core/CJsonLogLayout.cc:    writer.String(THREAD_NAME);
lib/core/CJsonLogLayout.cc:    writer.String(MESSAGE_NAME);
lib/core/CJsonLogLayout.cc:            writer.String(CLASS_NAME);
lib/core/CJsonLogLayout.cc:        writer.String(METHOD_NAME);
lib/core/CJsonLogLayout.cc:        writer.String(FILE_NAME);
lib/core/CJsonLogLayout.cc:        writer.String(LINE_NAME);
lib/core/CMemoryUsageJsonWriter.cc:    m_Writer.String(MEMORY);
lib/core/CMemoryUsageJsonWriter.cc:        m_Writer.String(UNUSED);
lib/core/CProgramCounters.cc:    writer.String(NAME_TYPE);
lib/core/CProgramCounters.cc:    writer.String(DESCRIPTION_TYPE);
lib/core/CProgramCounters.cc:    writer.String(COUNTER_TYPE);
```

(I am not saying every single one of those should have `Key` changed to `String` - some of those might be hardcoded values.  But at least some of those `grep` results are for field names.)

**Closed** 2022-12-21 15:52 UTC
Labels: :ml, >refactoring, good first issue
